### ISSUE TITLE
Add process to build dependencies before running tests in symlinked environment

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/ci#7]
Background: Pull request validation uses local clones of all source repositories and creates symbolic links to package dependencies in the parent `node_modules` directories. The purpose of this is to compare the most up-to-date changes across repositories.

Since packages (e.g. [truffle-contract](https://github.com/trufflesuite/truffle-contract)) may be distributed in bundled form, this bundle can be out of date with the changes on a given branch.

To avoid requiring that PR authors constantly commit manually built bundles, this CI process should perform that step automatically.

This will require having a single, standard `scripts` command defined in the corresponding `package.json`. (Right now, e.g., [truffle's](https://github.com/trufflesuite/truffle/blob/develop/package.json#L34) build script name is different than [truffle-contract's](https://github.com/trufflesuite/truffle-contract/blob/develop/package.json#L8).) It may be worth discussing whether or not we want to take this opportunity to remove build artifacts from source control, standardizing on an NPM `prepublish` step or the like.

**Comment by tcoulter** [comment]
>  It may be worth discussing whether or not we want to take this opportunity to remove build artifacts from source control, standardizing on an NPM prepublish step or the like.

Open to this, of course. Would love to keep make a separate concern so we can tackle individually.

**Comment by gnidan** [comment]
I believe @cgewecke did this via the `prepare` hook. Closing!
